### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SWoto** [mypiandrew/nfuse-lora#1]
@mypiandrew, you repo has no license, so I need to ask you... Could you please add one and/or let me copy and change this repository?
I'm working with this n-fuse card and I would like to use it.

Thank you for the great work.

**Comment by mypiandrew** [comment]
Hi

Feel free to fork it :-)

If there’s any thing broken be a good egg and feed it back so I can update

**Comment by SWoto** [comment]
Thank you, you can count on me.
